# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/linjx/afm_proj/Stratega

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/linjx/afm_proj/Stratega

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"bin\" \"dev\" \"devel\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/linjx/afm_proj/Stratega/CMakeFiles /Users/linjx/afm_proj/Stratega//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/linjx/afm_proj/Stratega/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/linjx/afm_proj/Stratega/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sfml-system

# Build rule for target.
sfml-system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-system
.PHONY : sfml-system

# fast build rule for target.
sfml-system/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/System/CMakeFiles/sfml-system.dir/build.make _deps/sfml-build/src/SFML/System/CMakeFiles/sfml-system.dir/build
.PHONY : sfml-system/fast

#=============================================================================
# Target rules for targets named sfml-window

# Build rule for target.
sfml-window: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-window
.PHONY : sfml-window

# fast build rule for target.
sfml-window/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Window/CMakeFiles/sfml-window.dir/build.make _deps/sfml-build/src/SFML/Window/CMakeFiles/sfml-window.dir/build
.PHONY : sfml-window/fast

#=============================================================================
# Target rules for targets named sfml-graphics

# Build rule for target.
sfml-graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-graphics
.PHONY : sfml-graphics

# fast build rule for target.
sfml-graphics/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build.make _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build
.PHONY : sfml-graphics/fast

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml_cpp-build/CMakeFiles/format.dir/build.make _deps/yaml_cpp-build/CMakeFiles/format.dir/build
.PHONY : format/fast

#=============================================================================
# Target rules for targets named yaml-cpp

# Build rule for target.
yaml-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp
.PHONY : yaml-cpp

# fast build rule for target.
yaml-cpp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml_cpp-build/CMakeFiles/yaml-cpp.dir/build.make _deps/yaml_cpp-build/CMakeFiles/yaml-cpp.dir/build
.PHONY : yaml-cpp/fast

#=============================================================================
# Target rules for targets named releasable

# Build rule for target.
releasable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 releasable
.PHONY : releasable

# fast build rule for target.
releasable/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml_cpp-build/CMakeFiles/releasable.dir/build.make _deps/yaml_cpp-build/CMakeFiles/releasable.dir/build
.PHONY : releasable/fast

#=============================================================================
# Target rules for targets named debuggable

# Build rule for target.
debuggable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debuggable
.PHONY : debuggable

# fast build rule for target.
debuggable/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml_cpp-build/CMakeFiles/debuggable.dir/build.make _deps/yaml_cpp-build/CMakeFiles/debuggable.dir/build
.PHONY : debuggable/fast

#=============================================================================
# Target rules for targets named googletest_project

# Build rule for target.
googletest_project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 googletest_project
.PHONY : googletest_project

# fast build rule for target.
googletest_project/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml_cpp-build/test/CMakeFiles/googletest_project.dir/build.make _deps/yaml_cpp-build/test/CMakeFiles/googletest_project.dir/build
.PHONY : googletest_project/fast

#=============================================================================
# Target rules for targets named run-tests

# Build rule for target.
run-tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run-tests
.PHONY : run-tests

# fast build rule for target.
run-tests/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml_cpp-build/test/CMakeFiles/run-tests.dir/build.make _deps/yaml_cpp-build/test/CMakeFiles/run-tests.dir/build
.PHONY : run-tests/fast

#=============================================================================
# Target rules for targets named parse

# Build rule for target.
parse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parse
.PHONY : parse

# fast build rule for target.
parse/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml_cpp-build/util/CMakeFiles/parse.dir/build.make _deps/yaml_cpp-build/util/CMakeFiles/parse.dir/build
.PHONY : parse/fast

#=============================================================================
# Target rules for targets named read

# Build rule for target.
read: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 read
.PHONY : read

# fast build rule for target.
read/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml_cpp-build/util/CMakeFiles/read.dir/build.make _deps/yaml_cpp-build/util/CMakeFiles/read.dir/build
.PHONY : read/fast

#=============================================================================
# Target rules for targets named sandbox

# Build rule for target.
sandbox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sandbox
.PHONY : sandbox

# fast build rule for target.
sandbox/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml_cpp-build/util/CMakeFiles/sandbox.dir/build.make _deps/yaml_cpp-build/util/CMakeFiles/sandbox.dir/build
.PHONY : sandbox/fast

#=============================================================================
# Target rules for targets named ImGUI

# Build rule for target.
ImGUI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ImGUI
.PHONY : ImGUI

# fast build rule for target.
ImGUI/fast:
	$(MAKE) $(MAKESILENT) -f dependencies/imgui/CMakeFiles/ImGUI.dir/build.make dependencies/imgui/CMakeFiles/ImGUI.dir/build
.PHONY : ImGUI/fast

#=============================================================================
# Target rules for targets named DebugUtils

# Build rule for target.
DebugUtils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DebugUtils
.PHONY : DebugUtils

# fast build rule for target.
DebugUtils/fast:
	$(MAKE) $(MAKESILENT) -f dependencies/recastNavigation/DebugUtils/CMakeFiles/DebugUtils.dir/build.make dependencies/recastNavigation/DebugUtils/CMakeFiles/DebugUtils.dir/build
.PHONY : DebugUtils/fast

#=============================================================================
# Target rules for targets named Detour

# Build rule for target.
Detour: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Detour
.PHONY : Detour

# fast build rule for target.
Detour/fast:
	$(MAKE) $(MAKESILENT) -f dependencies/recastNavigation/Detour/CMakeFiles/Detour.dir/build.make dependencies/recastNavigation/Detour/CMakeFiles/Detour.dir/build
.PHONY : Detour/fast

#=============================================================================
# Target rules for targets named DetourCrowd

# Build rule for target.
DetourCrowd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DetourCrowd
.PHONY : DetourCrowd

# fast build rule for target.
DetourCrowd/fast:
	$(MAKE) $(MAKESILENT) -f dependencies/recastNavigation/DetourCrowd/CMakeFiles/DetourCrowd.dir/build.make dependencies/recastNavigation/DetourCrowd/CMakeFiles/DetourCrowd.dir/build
.PHONY : DetourCrowd/fast

#=============================================================================
# Target rules for targets named DetourTileCache

# Build rule for target.
DetourTileCache: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DetourTileCache
.PHONY : DetourTileCache

# fast build rule for target.
DetourTileCache/fast:
	$(MAKE) $(MAKESILENT) -f dependencies/recastNavigation/DetourTileCache/CMakeFiles/DetourTileCache.dir/build.make dependencies/recastNavigation/DetourTileCache/CMakeFiles/DetourTileCache.dir/build
.PHONY : DetourTileCache/fast

#=============================================================================
# Target rules for targets named Recast

# Build rule for target.
Recast: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Recast
.PHONY : Recast

# fast build rule for target.
Recast/fast:
	$(MAKE) $(MAKESILENT) -f dependencies/recastNavigation/Recast/CMakeFiles/Recast.dir/build.make dependencies/recastNavigation/Recast/CMakeFiles/Recast.dir/build
.PHONY : Recast/fast

#=============================================================================
# Target rules for targets named Stratega

# Build rule for target.
Stratega: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Stratega
.PHONY : Stratega

# fast build rule for target.
Stratega/fast:
	$(MAKE) $(MAKESILENT) -f Stratega/CMakeFiles/Stratega.dir/build.make Stratega/CMakeFiles/Stratega.dir/build
.PHONY : Stratega/fast

#=============================================================================
# Target rules for targets named Arena

# Build rule for target.
Arena: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Arena
.PHONY : Arena

# fast build rule for target.
Arena/fast:
	$(MAKE) $(MAKESILENT) -f Arena/CMakeFiles/Arena.dir/build.make Arena/CMakeFiles/Arena.dir/build
.PHONY : Arena/fast

#=============================================================================
# Target rules for targets named GUI

# Build rule for target.
GUI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GUI
.PHONY : GUI

# fast build rule for target.
GUI/fast:
	$(MAKE) $(MAKESILENT) -f GUI/CMakeFiles/GUI.dir/build.make GUI/CMakeFiles/GUI.dir/build
.PHONY : GUI/fast

#=============================================================================
# Target rules for targets named Tests

# Build rule for target.
Tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tests
.PHONY : Tests

# fast build rule for target.
Tests/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/Tests.dir/build.make Tests/CMakeFiles/Tests.dir/build
.PHONY : Tests/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... debuggable"
	@echo "... format"
	@echo "... googletest_project"
	@echo "... releasable"
	@echo "... Arena"
	@echo "... DebugUtils"
	@echo "... Detour"
	@echo "... DetourCrowd"
	@echo "... DetourTileCache"
	@echo "... GUI"
	@echo "... ImGUI"
	@echo "... Recast"
	@echo "... Stratega"
	@echo "... Tests"
	@echo "... parse"
	@echo "... read"
	@echo "... run-tests"
	@echo "... sandbox"
	@echo "... sfml-graphics"
	@echo "... sfml-system"
	@echo "... sfml-window"
	@echo "... yaml-cpp"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/linjx/afm_proj/Stratega/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

