[build-system]
requires = [
   "setuptools>=61",
   "setuptools_scm>=6.2",
   "wheel",
   "cmake>=3.18",
   "pybind11~=2.6.1",
   "ninja; sys_platform != 'win32'",
]
build-backend = "setuptools.build_meta"
